### ISSUE TITLE
Proper live period-determination

### ISSUE THREAD

**Issue by jmtayloruk** [Glasgow-ICG/open-optical-gating#10]
At the moment the code accumulates a fixed (large) number of frames before attempting to calculate the period in one big chunk of processing in establish_indices(). This is not going to work well live, when we want to lock on to a period ASAP, rather than acquiring an unnecessarily long frame buffer first.

**Comment by jmtayloruk** [comment]
Otherwise, apart from anything else, we will end up acquiring significantly more frames than we need to before we can establish a period. There are also scenarios where this approach will fail, where it could succeed if it was allowed just to keep trying indefinitely, processing a rolling buffer of recent frames. (Minor related observation: once that is changed, and the loop is removed from this function, the "didn't find a period" error will not be "critical" when running live)

**Comment by ChasNelson1990** [comment]
So... I am now remembering why this was done this way and it's because Numpy arrays don't like to be appended to and I didn't want to keep np.array-ing a list. I can't think of a better way so have used np.append - it adds about 0.5 seconds on the total compute time for the example emulation.

**Comment by jmtayloruk** [comment]
As discussed earlier, I am pretty sure we can do this using a list of 2D arrays, without that causing any inconvenience. If I need to update jps to accept a list, I can do that easily.

**Comment by jmtayloruk** [comment]
As discussed earlier, I am pretty sure we can do this using a list of 2D arrays, without that causing any inconvenience. If I need to update jps to accept a list, I can do that easily.

**Comment by jmtayloruk** [comment]
There is a related consideration that we might want to think about and discuss before diving in to anything: just as refBuffer is currently a preallocated 3D array holding the frame data, frameHistory is a preallocated 2D array holding what is effectively frame metadata. I think the right solution here (see also my prior comments in the main pull discussion) is probably actually to have a list of {frame+metadata} entities.

I don't have particularly strong views on what those entities should look like. My ImageClass object (in j_postacquisition) is probably overkill here, but a class object would be one way to go with this. Another option would be just to have an (ndarray, dict) tuple for pixel data and metadata.

As far as I can see, the only time we make use of the 2D-array-ness of the "frameHistory" metadata is when doing the linear fitting of phase vs time. To extract 1D arrays from the list, we would need to create a new array (using e.g. a list comprehension). On paper this is kind of inefficient, but I would be surprised if it actually proved to be a true bottleneck.

On the one hand the current code is not broken, but on the other hand I think this would tidy it up a lot for future development and current readability. What do you reckon?

**Comment by jmtayloruk** [comment]
In the current code, note also that self.timestamp, self.phase etc duplicate the information that is in frameHistory. There is no need for that.

If there's a worry about not keeping a large enough frame history when intending to call e.g. plot_accuracy, I suggest we just increase the limit on the frame buffer size. If that's going to be a problem in terms of keeping around huge amounts of frame data when we just want the metadata, we might need to come up with a slightly different plan for that, but I'm sure we can manage something.

**Comment by ChasNelson1990** [comment]
Yes. I also came across the other buffer whilst todoing things this afternoon. I think, based on all we've discussed, a list of ndarrays with custom attributes could be the cleanest solution. I feel a list of lists of [ndarray, list] becomes a bit messy? (I guess all the inner lists would actually be tuples to prevent over-writing but still). Any custom ndarray could essentially be edited to match anything of your ImageClass that you decide later to bring in?

**Comment by jmtayloruk** [comment]
I had intended the metadata to be a dictionary, not a list or tuple, i.e. list of (frame, dict) tuples. But I'm certainly happy to agree that that's a bit messy.

I'd forgotten that we reckoned the custom ndarray option should work. I'm still a bit wary in principle about it being fragile (losing attributes if we transform the pixel array in some way), but I appreciate that in practice we're probably not going to do that. I recommend that we add a _single_ attribute which is a dictionary containing all the metadata. Loads of separate attributes would feel more natural for this C++ programmer, but I think a dict is the right way to do this in python.

Incidentally I've done a performance test, and I can create an array containing the "phase" attributes drawn from a list-of-200-custom-ndarrays in about 50µs, so I am not concerned about creating an unnecessary performance bottleneck.

Assuming you're happy with that, on to the more trivial question: what to call it? ImageClass would be ok by me, or perhaps PixelArray? I'm not keen on ImageArray as that sounds to me like an array of images.

**Comment by ChasNelson1990** [comment]
MetaFrame! Because it's metadata and a frame and sounds like a transformer ;-)
Also.... https://pillow.readthedocs.io/en/stable/reference/Image.html (ctrl+F for Image.info)...

**Comment by jmtayloruk** [comment]
Tempting...

In terms of "Image", I'm not sure exactly what I'm meant to be looking at. I do **not** think we should use that object as our frame+metadata object, because it looks very hard to access raw pixels, and it's too general as a class. It looks to me like a class that's designed for coping with different colour channels etc, in a way that's going to get in our way rather than being helpful. I think building on an ndarray, in some way or other, is the right thing to do.

But I do certainly see that what they are doing with Image.info is exactly what we are talking about doing with PixelArray.metadata.

**Comment by jmtayloruk** [comment]
Resolved a while ago...
