### ISSUE TITLE
Properly debug the type mismatch issues on the RPi

### ISSUE THREAD

**Issue by jmtayloruk** [Glasgow-ICG/open-optical-gating#16]
See phase_matching() in prospective_optical_gating.py. There are unnecessary casts to uint8 which appear to be workarounds for a (historical?) bug somewhere in the RPi code. Please can this be properly debugged so that these casts can be eliminated?

Apart from anything else, I would like to be able to support uint16 frames too, and these casts are scuppering that intention.

**Comment by jmtayloruk** [comment]
In terms of the comment "to stop jps falling down on types", I believe that jps will only complain if you really do pass it the wrong types - and so the issue is in the RPi code. But if you think there is a problem with jps, let me know the details - the error messages should be fairly informative these days.

**Comment by jmtayloruk** [comment]
In terms of the comment "to stop jps falling down on types", I believe that jps will only complain if you really do pass it the wrong types - and so the issue is in the RPi code. But if you think there is a problem with jps, let me know the details - the error messages should be fairly informative these days.

**Comment by ChasNelson1990** [comment]
So @abdrysdale can correct me if I'm misremembering here but the problem here was that if we did `print(array.dtype)` on a frame from the live picamera it said 'np.uint8'... but jps gave a type error. If we wrapped the array in a cast and did another `print(array.dtype)` both prints showed `np.uint8` but now jps did not through a type error. At the time, you said it could be a stride issue?
P.S. This is not replicable with saved frames from the picamera, only live ones.

**Comment by jmtayloruk** [comment]
Ah yes, I remember speculating about strides.

It would be great to reproduce and debug this. As I say, I'd very much like to be able to remove these casts at this point - even if it ends up that we have to put them somewhere RPi-specific such as at the very start of the analyze() function. JPS should be fairly specific about the errors it reports, these days at least. If you can devise a reproducible scenario, I would like to work out what is going on.

Update: I've just tested, and if there is a stride problem then JPS _should_ currently be reporting e.g.:
exceptions.TypeError: Expected array 1 to be contiguous in x s[0]=42 s[1]=2 sizeof(type)=1 itemsize=1

**Comment by ChasNelson1990** [comment]
Because this was non-reproducible with saved files, we may need to wait until we have fish for this?

If you need uint16 for the WebSocket work, feel free to change these castes to uint16 until we can test this live?

**Comment by jmtayloruk** [comment]
Might be testable by pointing a live RPi camera at "nothing"? Won't get sync, but will be calling jps...

**Comment by abdrysdale** [comment]
Yes, that' how I remember it @ChasNelson1990. 

With the regards to the pointing the camera at nothing, that might help with integrating some tests for some test driven development.

**Comment by ChasNelson1990** [comment]
@abdrysdale do you think you'd have some time for the following:

1. A quick chat about what needs to be done to get the PiOpticalGater working again? I think I know what to do but would be good to bounce the idea off of you.
2. Starting to put some tests together (ideally for the base OpticalGater as well as FileOpticalGater and PiOpticalGater)? I think if you can set-up a pytest framework and start building some tests then @jmtayloruk and @ChasNelson1990 should be able to come in and build on that over the next couple of weeks.

**Comment by abdrysdale** [comment]
> @abdrysdale do you think you'd have some time for the following:
> 
> 1. A quick chat about what needs to be done to get the PiOpticalGater working again? I think I know what to do but would be good to bounce the idea off of you.
> 2. Starting to put some tests together (ideally for the base OpticalGater as well as FileOpticalGater and PiOpticalGater)? I think if you can set-up a pytest framework and start building some tests then @jmtayloruk and @ChasNelson1990 should be able to come in and build on that over the next couple of weeks.
 
1. Yes. I can do anytime Sarurday.
2. Sounds great, I've not got any experience in doing that but I'd love to give it a go.

**Comment by jmtayloruk** [comment]
> If you need uint16 for the WebSocket work, feel free to change these castes to uint16 until we can test this live?

Given that the pi stuff evidently needs work anyway, I propose just to *remove* those casts. That way the rest of the codebase won't be affected by them. If you hit problems again when testing the RPi, we can debug and/or reintroduce the casts on receipt of the frame buffer, in PiOpticalGater.analyze().

**Comment by jmtayloruk** [comment]
Things seem fixed now - removing the casts has not caused any problems
