### ISSUE TITLE
Add support for barrier frames

### ISSUE THREAD

**Issue by jmtayloruk** [Glasgow-ICG/open-optical-gating#9]
Barrier frames are not being implemented properly. There is a call to determine_barrier_frames, but I don't think the *value* for the barrier frame parameter is ever computed. It certainly isn't when using existing reference frames. This seems like an important missing bit of code. I think it just defaults to 0 when the settings are initialised, and stays that way.

_Originally posted by @ChasNelson1990 in https://github.com/_render_node/MDE3OlB1bGxSZXF1ZXN0UmV2aWV3NDY4MjcxOTQw/pull_request_reviews/more_threads_

**Comment by ChasNelson1990** [comment]
Are you sure about this @jmtayloruk? (The following line number refer to commit 89e096 in the get_period branch)

When we set-up the period we call `self.pog_settings = pog.determine_barrier_frames(self.pog_settings)`, which determines a list of barrier frames for each period frame (e.g. line 400 of optical_gater_server.py). This list lives inside pog_settings as `frameToUseArray`.

Then, whenever we call `timeToWaitInSecs = pog.predict_trigger_wait(self.frame_history[: self.frame_num :, :], self.pog_settings, fitBackToBarrier=True)` which uses `frameToUseArray` on line 254 of prospective_optical_gating.py.

**Comment by jmtayloruk** [comment]
Yes, I am almost certain about it. I've checked twice now. That (perhaps misleadlingly-named) function just precalculates some arrays that are used in the barrier frame processing. Nobody ever actually computes the correct value for parameters["barrierFrame"] at the point when the reference sequence is established.

I suppose it's possible that you expect the user to just manually designate that at the same time as they choose a target reference frame. But ObjC code exists to empirically identify the barrier frame based on the characteristics of the image sequence, and I'm 99% sure that is not present in the python code.
